######################################## 定时任务配置 ####################################
energy:
  # 园区概况 每天晚上8点10分执行
  partinfo: '0 10 20 * * ?'
  # 环境概况 每天晚上8点10分执行
  enviromentinfo: '0 15 20 * * ?'
  # 重要事情 每天晚上8点10分执行
  importantevents: '0 20 20 * * ?'
  # 近一周用电负荷异常 每天晚上8点10分执行
  eleexception:  '0 25 20 * * ?'
  # 能耗概况 每天晚上8点10分执行
  energyinfo: '0 30 20 * * ?'
  # 消费概况 每天晚上8点10分执行
  fireinfo: '0 35 20 * * ?'
  # 火情告警 每天晚上8点10分执行
  firealarm: '0 40 20 * * ?'